<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MY-PC" name="com.Actouch.SalesINV.TestSrcipt.Receivable" tests="11" failures="1" timestamp="10 Feb 2017 11:14:58 GMT" time="741.279" errors="0">
  <testcase name="AR_Disc_INR_TC_8" time="80.888" classname="com.Actouch.SalesINV.TestSrcipt.Receivable"/>
  <testcase name="AR_Partial_Recevable_Cash_TC_2" time="59.095" classname="com.Actouch.SalesINV.TestSrcipt.Receivable"/>
  <testcase name="AR_Full_Recevable_Cheque_TC_3" time="59.594" classname="com.Actouch.SalesINV.TestSrcipt.Receivable"/>
  <testcase name="AR_Disc_percentage_TC_7" time="55.928" classname="com.Actouch.SalesINV.TestSrcipt.Receivable"/>
  <testcase name="AR_VoucherAdjustment_TC_10" time="57.692" classname="com.Actouch.SalesINV.TestSrcipt.Receivable"/>
  <testcase name="AR_Partial_Recevable_Cheque_TC_4" time="67.675" classname="com.Actouch.SalesINV.TestSrcipt.Receivable"/>
  <testcase name="AR_Full_Recevable_Cash_TC_1" time="71.570" classname="com.Actouch.SalesINV.TestSrcipt.Receivable"/>
  <testcase name="AR_Adjust_Payment_Advanced_TC_5" time="63.682" classname="com.Actouch.SalesINV.TestSrcipt.Receivable"/>
  <testcase name="AR_Adjust_Payment_SaleReturn_TC_6" time="127.706" classname="com.Actouch.SalesINV.TestSrcipt.Receivable">
    <failure type="java.lang.AssertionError" message="total amount not correct expected [0.00] but found [10.00]">
      <![CDATA[java.lang.AssertionError: total amount not correct expected [0.00] but found [10.00]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at com.Actouch.SalesINV.TestSrcipt.Receivable.AR_Adjust_Payment_SaleReturn_TC_6(Receivable.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- AR_Adjust_Payment_SaleReturn_TC_6 -->
  <testcase name="AR_Roundoff_TC_9" time="78.923" classname="com.Actouch.SalesINV.TestSrcipt.Receivable"/>
  <testcase name="salesIN_Login_TC_1" time="18.526" classname="com.Actouch.SalesINV.TestSrcipt.Receivable"/>
</testsuite> <!-- com.Actouch.SalesINV.TestSrcipt.Receivable -->
